import matplotlib.pyplot as plt
import numpy as np
phi = np.loadtxt("fort.11")
plt.title('Eigenfunction')
plt.ylabel(r"$\Re(\phi(y))$, $\Im(\phi(y))$")
plt.xlabel(r"$y$")
plt.plot(phi[:,0],phi[:,1],'b-',label=r"$\Re(\phi(y))$")
plt.plot(phi[:,0],phi[:,2],'r-',label=r"$\Im(\phi(y))$")
plt.tick_params(axis='x',direction='in')
plt.tick_params(axis='y',direction='in')
plt.xticks(np.arange(0,18,2))
plt.yticks(np.arange(-0.2,1.2,.2))
#plt.axis([0, 20, -.5, 1])
plt.legend()
plt.savefig("phi.png")
plt.show(block=False)
